<?php 
/**
 * @category    Mana
 * @package     Mana_Filters
 * @copyright   Copyright (c) http://www.manadev.com
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
/** 
 * Template for showing options for filter as a HTML list 
 * @author Mana Team
 * Injected instead of standard catalog/layer/filter.phtml in Mana_Filters_Block_Filter_Attribute constructor.
 * This template is overridden by copying (template body was pasted from catalog/layer/filter.phtml 
 * and modified as needed). All changes are marked with comments.
 */
/* @var $this Mana_Filters_Block_Filter_Attribute */
?>
<?php
	$num=5;
?>
<ol class="filter-item-list <?php if(count($this->getItems())>$num) echo ' scrollable'; else echo ' unscroll'?>">
<?php foreach ($this->getItems() as $_item): ?>
    <li <?php if ($_item->getMSelected()): ?>class="selected-ln-item"<?php else:?> class="select-ln-item" <?php endif; ?>>
        <?php // MANA BEGIN ?>
        <?php if ($_item->getMSelected()): ?>
        	<div class="selected-filter-item"><span></span><?php echo $_item->getLabel() ?></div>
        <?php else : ?>
	        <?php if ($_item->getCount() > 0): ?>
	        	<div class="select-filter-item"><a href="<?php echo $this->urlEscape($_item->getReplaceUrl()) ?>" title="<?php echo $_item->getLabel() ?>"><span></span><?php echo $_item->getLabel() ?></a></div>
	        <?php else: ?><div class="non-select-filter-item"><span></span><?php echo $_item->getLabel() ?></div>
	        <?php endif; ?>
        <?php endif; ?>
        <?php // MANA END ?>
        <em>(<?php echo $_item->getCount() ?>)</em>
    </li>
<?php endforeach ?>
</ol>
<?php echo Mage::helper('mana_core')->getNamedHtml('mana_filters/markup', 'after_items', array('block' => $this)) ?>
