<?php
/**
 * Easy Checkout - Magento Extension
 *
 * @package     EasyCheckout
 * @category    EcommerceTeam
 * @copyright   Copyright 2011 EcommerceTeam Inc. (http://www.ecommerce-team.com)
 * @version:    1.3.5
 */
?>
<?php $order = $this->getOrder();?>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head"><?php echo $this->__('Customer Comment') ?></h4>
    </div>
    <fieldset>
        <?php echo nl2br($order->getCustomerComment()); ?>
    </fieldset>
</div>
