<?php
/**
 * @copyright  Copyright (c) 2011 Capacity Web Solutions Pvt. Ltd  (http://www.capacitywebsolutions.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<style>
.productList { float:left; width:720px; }
.productList .product { background:#fff; border:1px solid #ccc; padding:5px;  float:left; margin:10px 8px 10px 0; text-align:center; }
.productList .product .cl { padding:0 0 0 0px; text-align:center;}
.productList .product .prodDetails {text-align:center; padding:0 0 0 0px;  }
.productList .product .addCompare { text-align:center;  clear:both; }
.productList .product .addWishlist {clear:both; text-align:center; }
</style>
<?php
	$result = $this->getBestsellerProduct();
	$upperLimit = ($this->getLimit()) ? $this->getLimit() : 1; 
	$itemPerRow = ($this->getItemsPerRow()) ? $this->getItemsPerRow() : 1 ;
	$model = Mage::getModel('catalog/product');
	$enabled = Mage::getStoreConfig('bestseller/general/enabled'); 
	$products_price = Mage::getStoreConfig('bestseller/general/products_price');  
	$review = Mage::getStoreConfig('bestseller/general/review'); 
	$out_of_stoke = Mage::getStoreConfig('bestseller/general/out_of_stoke');  
?>
<?php if($enabled == 1): ?>
	<?php if($result):?> 
    <div class="bestSeller">
    	<h2><?php echo $this->getHeader(); ?></h2>
       	<ul class="main-list product_list best_selling_product">
            <?php if ($out_of_stoke == 0) { ?>
              <?php
                $i=0; $x = 1;
                for($cnt = 0; $cnt<count($result); $cnt++)
                {
                    $_product = $model->load($result[$cnt]);  //getting product object for particular product id
                    $status =  $_product->getData('status');
                    $is_salable = $_product->getData('is_salable');
                    if($status == 1)
                    {	 
                     if ($is_salable == 1 )
                     {  
                      if($x <= $upperLimit)
                      {
                       if($i>($itemPerRow-1))
                         echo '<li valign="top">';
              ?>
                <li class="anim_border_wrap">
                    <div class="productImgDivWrap new_img">
                        <p class="showImg">
                            <span class="quickViewBtn quickViewBtnShowing" style="display: none;"></span>
                            <a href="<?php echo $this->getBaseUrl().$_product['url_path']; ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>">
                                <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(($this->getImageHeight()) ? $this->getImageHeight() : 135,($this->getImageWidth()) ? $this->getImageWidth() : 135); ?>" alt="<?php echo $this->htmlEscape($_product['name']) ?>"/>
                            </a>
                        </p>      
                    </div>
                    <div class="new_content">
                        <h3 class="arrival_name">
                            <?php echo $this->htmlEscape($_product['name']) ?>
                        </h3>
                        <div class="summary">
                            <span class="msrp">
                            <?php echo Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol(). number_format($_product->getFinalPrice(),2);?>
                        	</span>
                        	<span class="sub_title"><?php echo $_product->getSku();?></span>                        
						</div>
                        <div class="hover_bottom" style="bottom: -36px;">
                            <div class="favorite">
                                <?php
                                    $resource = Mage::getSingleton('core/resource');
                                    $readConnection = $resource->getConnection('core_read');
                                    $wishlist = $readConnection->fetchAll('SELECT product_id, count(*) as total FROM wishlist_item GROUP BY product_id');
                                    foreach($wishlist as $item){
                                        $wish[$item['product_id']]=$item['total'];
                                    }
                                    if($wish[$_product->getId()]){
                                        echo $wish[$_product->getId()];
                                    }
                                    else
                                    {
                                        echo '0';
                                    }
                                ?>
                            </div>
                            <div class="social"></div>
                        </div>	
                    </div>
                    <div class="anim_border t" style="overflow: hidden;"></div>
                    <div class="anim_border b" style="overflow: hidden;"></div>
                    <div class="anim_border l" style="overflow: hidden;"></div>
                    <div class="anim_border r" style="overflow: hidden;"></div>
                </li>
                 <?php
                    $i++;
                        if($i>($itemPerRow-1))
                        {
                            $i=0;
                        }
                            if($i==($itemPerRow))
                        { 
                            
                        }
                       }
                     $x++;
                     }
                    }		
                } 
               ?>
            <?php
            }
            else
            {?>
              <li class="anim_border_wrap">
                    <div class="productImgDivWrap new_img">
                        <p class="showImg">
                            <span class="quickViewBtn quickViewBtnShowing" style="display: none;"></span>
                            <a href="<?php echo $this->getBaseUrl().$_product['url_path']; ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>">
                                <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(($this->getImageHeight()) ? $this->getImageHeight() : 135,($this->getImageWidth()) ? $this->getImageWidth() : 135); ?>" alt="<?php echo $this->htmlEscape($_product['name']) ?>"/>
                            </a>
                        </p>      
                    </div>
                    <div class="new_content">
                        <h3 class="arrival_name">
                            <?php echo $this->htmlEscape($_product['name']) ?>
                        </h3>                   
                        <span class="row fw-bold">
                            <?php echo Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol(). number_format($_product->getFinalPrice(),2);?>
                        </span>
                        <span><?php echo $_product->getSku();?></span>                        
                        <p class="row" id="text_<?php echo $_product->getSku();?>"></p>
                        <div class="hover_bottom" style="bottom: -36px;">
                            <div class="favorite">22</div>
                            <div class="social"></div>
                        </div>
                    </div>
                    <div class="anim_border t" style="overflow: hidden;"></div>
                    <div class="anim_border b" style="overflow: hidden;"></div>
                    <div class="anim_border l" style="overflow: hidden;"></div>
                    <div class="anim_border r" style="overflow: hidden;"></div>
                </li>
            <?php
            }
            ?>
        </ul>
        <div class="count_wishlist">
			<?php
                //$resource = Mage::getSingleton('core/resource');
                //$readConnection = $resource->getConnection('core_read');
                //$total_wishlist = $readConnection->fetchCol('SELECT count(*) FROM wishlist_item');
                //echo $total_wishlist[0];
            ?>
        </div>
	</div>
<?php endif; ?>
<?php endif; ?>