<div id="content_footer">
    <div class="social">
        <div class="content">
       		<div class="heading">Follow Citizen Eco-Drive</div>
            <div class="fb_like">
                <iframe src="http://www.facebook.com/plugins/like.php?href=http://www.facebook.com/kimchiquan&amp;send=false&amp;layout=button_count&amp;width=450&amp;show_faces=false&amp;action=like&amp;colorscheme=light&amp;font&amp;height=21" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:450px; height:21px;" allowtransparency="true"></iframe>
            </div>
            <div class="twitter_follow">
                <iframe id="twitter-widget-0" scrolling="no" frameborder="0" allowtransparency="true" src="http://platform.twitter.com/widgets/follow_button.1392079123.html#_=1393578575309&amp;id=twitter-widget-0&amp;lang=en&amp;screen_name=CitizenEcoDrive&amp;show_count=true&amp;show_screen_name=false&amp;size=m" class="twitter-follow-button twitter-follow-button" title="Twitter Follow Button" data-twttr-rendered="true" style="width: 159px; height: 20px;"></iframe>
                <script>!function(d, s, id) {
                    var js, fjs = d.getElementsByTagName(s)[0];
                    if (!d.getElementById(id)) {
                    js = d.createElement(s);
                    js.id = id;
                    js.src = "//platform.twitter.com/widgets.js";
                    fjs.parentNode.insertBefore(js, fjs);
                    }
                }(document, "script", "twitter-wjs");</script>
            </div>
        </div>
    </div>
    <div class="watch_ticker">
        <ul>
            <li class="ticker_item">
                <a href="#" title="">
                    <div class="fav_count">
                        <div><span class="count">1253 </span>people favorited:</div>
                    </div>
                   	<div class="img_wrapper">
                        <img src="http://c01.coacdn.com/watches/AT4007-54E_thumb.png">
                    </div>
                    <div class="info">
                        <span>AT4007-54E</span>
                    </div>
                </a>
            </li>
        </ul>
    </div>
    <div class="view_all">
        <div class="content">
        	<a href="http://www.citizenwatch.com/en-us/watches/find-a-watch" title="Find a Watch">Find a Watch</a>
        </div>
    </div>
</div>