<div class="PDPReviewBox-2">            
    <div class="PDPReviewTop-2">
        <div class="PDPReviewTitleBox-2">
            <span class="PDPReviewTitle-2"></span>
            <span class="right"><?php echo $this->__('Hãy viết nhận xét về sản phẩm, hoặc bất kỳ thắc mắc gì tại đây. OMEGAMART sẽ cố gắng giải đáp nhanh nhất')?></span>        
            <div class="clearFloatNoHeight"></div>
            <div class="greyDoubleLine"></div>
        </div>
        <div class="PDPReviewContent-2">                
                <div class="clearFloatNoHeight"></div>
                <div class="videoTabContent">
                    <div id="ManufacturerDetailInfo" class="content" style="display: none;"></div>
                    <div id="ConsumerDetailInfo" class="content" style=""><div class="clearFloatNoHeight"></div>
                </div>
            </div>
            <div class="reviewTabBox">
                <div class="reviewTabTitle" style="display:none"></div>
                <div class="reviewSnapshot" style="display:block;">
                    <p class="reviewSnapshotTitle"></p>
					<div class="fb-comments" data-width="927" data-num-posts="10" href="<?php echo Mage::helper("core/url")->getCurrentUrl()?>"></div>                    
                </div>
            </div>
        </div>
    </div>
</div>