<script type="text/javascript">
//<![CDATA[
	if (typeof MP == 'undefined') MP = {};
	MP.QuickShop = {
		BASE_URL : '<?php echo str_replace("index.php/","",$this->getUrl()) ?>',
		QS_FRM_TYPE : <?php echo Mage::getStoreConfig('quickshop/general/size_type');?>,
		QS_FRM_WIDTH : <?php echo Mage::getStoreConfig('quickshop/general/frame_width');?>,
		QS_FRM_HEIGHT : <?php echo Mage::getStoreConfig('quickshop/general/frame_height');?>,
		QS_IMG: '<?php echo $this->getSkinUrl('images/omg/quickview.png'); ?>'
	};
	if(MP.QuickShop.QS_FRM_TYPE == 0 ){
		MP.QuickShop.QS_FRM_WIDTH = MP.QuickShop.QS_FRM_WIDTH + "%";
		MP.QuickShop.QS_FRM_HEIGHT = MP.QuickShop.QS_FRM_HEIGHT + "%";
	}

//]]	
</script> 
